theme: jekyll-theme-cayman
title: Github Pages Blog
author: Nocco Giovanni Emanuele
email: info@genocs.com
description: > # this means to ignore newlines until "baseurl:"
  Genocs github pages
# social links
twitter_username: NoccoGiovanni # DO NOT include the @ character, or else the build will fail!
github_username:  giovanninocco # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
